# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37d9b08cf20f9686363c1a4cf0e4066b50f7ff106deada91f1acb8e37cfea96a506c82a9a2f1bfdc13d19c81fe153551f44a9fe316fba50340ba22f8a60f6777

test:
  secret_key_base: 28739ec2f95be27d6dab0acd220f61b4dc43af7d36cbd3f6ed5416f11037540b599a15c2606c9bdef63bfaa8544c81d189a903e37ad18317cfefd94d92f540b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
